language: python

cache: pip

python:
  - 3.9
  - 3.10
  - 3.11
  - 3.12
  - 3.13
  - pypy3

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - pip install pipenv
  - pipenv install --dev --skip-lock

script:
  pipenv run pytest ./test_systemd_watchdog.py
